language: java
sudo: false

script: "mvn cobertura:cobertura"
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "nikola-popov-github" 
